### ISSUE TITLE
Doesn't recognize HTML in .jade file

### ISSUE THREAD

**Issue by codyrigney92** [tht13/html-preview-vscode#1]
It would be nice if it did because it would allow a jade file converted to html to work. It would be even better if it could convert to HTML automatically before preview without converting the original.

**Comment by tht13** [comment]
Fixed in 399da5f
Will be released shortly in v0.0.3

**Comment by codyrigney92** [comment]
Thanks!

**Comment by tht13** [comment]
Published :smile:
