### ISSUE TITLE
VSCode HTML preview extension not working

### ISSUE THREAD

**Issue by SaarahAnne** [tht13/html-preview-vscode#12]
I've just installed the preview extension for VSCode, and when I use the key command "ctrl + shft + h", this pops up instead of my preview:

"Active editor doesn't show a HTML or Jade document - no properties to preview."

**Comment by tht13** [comment]
What document did you have open when trying to preview?

**Comment by SaarahAnne** [comment]
I don't remember exactly anymore, but I think I solved the problem by saving the document as an .html and not a .txt file, which opened up in Google immediately (this is from what I can remember though...).
