### ISSUE TITLE
Preview - Style

### ISSUE THREAD

**Issue by byman64** [tht13/html-preview-vscode#13]
Who is doing the render of html pages.---just to know the level of compatibility.

I noted some not stadard stuff.
For example h1 tag is not standard, I mean size, font-family
Same for buttons
It's as if the preview applies a style sheet. I would like vanilla stuff if possible.

`<h1>This is sample title</h1>`

Preview show a different style compared to other browsers: chrome, edge and FF ...

Please let me know if I can reset something.

thanks

**Comment by tht13** [comment]
All extension applied style settings have been removed in v0.2.4 which should provide a vanilla environment. I will close this issue now, please let me know if you still have a problem and I will re-open.
