### ISSUE TITLE
HTML text previews in grey - can't read text

### ISSUE THREAD

**Issue by EnforcerZhukov** [tht13/html-preview-vscode#15]
I'm using this plugin, previewing a simple page returns this text - instead of black it's a grey - almost white color, which can't be read, as shown on the following screenshot:

![image](https://user-images.githubusercontent.com/17401854/30850633-60bd18d8-a2a6-11e7-9f7a-7a6b49ad06e3.png)

OS: Ubuntu Mate 16.04.2 LTS
VSCode version: 1.16.1

**Comment by Pino-Boom** [comment]
I want to know...oh...my English is poor....What if it's a chain entry?

**Comment by tht13** [comment]
Fixed in v0.2.4 
Default background is now transparent.
