### ISSUE TITLE
Everything is doubled

### ISSUE THREAD

**Issue by reszy** [tht13/html-preview-vscode#18]
Hi I have a problem with doubled text in preview.

### Examples
Code :
`<p>a</p><p>b</p>`
Result:
```
a
b
a
b
```
Code :
```
<p>a</p>
<p>b</p>
```
Result:
```
a
a
b
b
```

Im using
Extension version 0.2.4
VS Code version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by nils-ballmann** [comment]
Having the same issue.

**Comment by SimpleSamples** [comment]
Me too. I created a HTML file with only the following (no <html> or <body> or anything else):
`<p>Test of HTML Preview.</p>`
And I get:

Test of HTML Preview.

Test of HTML Preview.

If I remove the <p> tags then I don't get the double.

**Comment by tht13** [comment]
Same issue as https://github.com/tht13/RST-vscode/issues/10
Fixed in v0.2.5

**Comment by nsballmann** [comment]
Can confirm: Fixed
