### ISSUE TITLE
Toggle doesn't toggle

### ISSUE THREAD

**Issue by CodeCharm** [tht13/html-preview-vscode#2]
The `HTML:Toggle Preview` command (`html.preview`), whether I use the run command prompt, or the keyboard shortcut, works great when I'm looking at a plain HTML file in the editor. 

However, it doesn't actually "toggle" back to the source HTML after the preview appears. Instead, I have to cycle through open files (Ctrl+Tab) to get back to the HTML. If I run the `HTML:Toggle Preview` command (again, either from the run command prompt or with the `Ctrl+Shift+H` keyboard shortcut) while looking at the \Preview window, I get the message "Running the contributed command:'html.preview' failed."

I'm running VS Code 0.10.11

**Comment by tht13** [comment]
Toggle functionality has been disabled. Interactivity is much smoother and stability improved in v0.2.4
