### ISSUE TITLE
Conflicting keyboard shortcuts

### ISSUE THREAD

**Issue by agross** [tht13/html-preview-vscode#8]
Ctrl+Shift+H is bound to "Replace in files" on Windows. Installing this extension breaks this core feature of VS Code: As long as your're editing a non-HTML file nothing happens when you press the chord.

**Comment by tht13** [comment]
Keyboard shortcuts have been changed to use letter `v` instead of `h` in version v0.2.4. This reflects the functionality in the markdown preview.
